path_to_search: /Volumes/Qmultimedia/Movies/V/
host: '192.168.99.100'
prepend: /Volumes
preremove: /XXXXXXXXXX

truck:
    color: blue
    brand: ford
city: new york
cabriolet:
    color: black
    engine:
        cylinders: 8
        placement: mid
    doors: 2
